INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RDNT', 'RadNet')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RDWR', 'Radware Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('METC', 'Ramaco Resources')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RMBS', 'Rambus')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RAND', 'Rand Capital Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('GOLD', 'Randgold Resources Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RNDB', 'Randolph Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RPD', 'Rapid7')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RAVE', 'Rave Restaurant Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RAVN', 'Raven Industries')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RBB', 'RBB Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ROLL', 'RBC Bearings Incorporated')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RICK', 'RCI Hospitality Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RCMT', 'RCM Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RDI', 'Reading International Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RDIB', 'Reading International Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RGSE', 'Real Goods Solar')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('BCNA', 'Reality Shares Nasdaq NexGen Economy China ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('BLCN', 'Reality Shares Nasdaq NextGen Economy ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RLM', 'Realm Therapeutics plc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RNWK', 'RealNetworks')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RP', 'RealPage')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RETA', 'Reata Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RCON', 'Recon Technology')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('REPH', 'Recro Pharma')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RRGB', 'Red Robin Gourmet Burgers')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RRR', 'Red Rock Resorts')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RDVT', 'Red Violet')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RDFN', 'Redfin Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RDHL', 'Redhill Biopharma Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('REGN', 'Regeneron Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RGNX', 'REGENXBIO Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RGLS', 'Regulus Therapeutics Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RBNC', 'Reliant Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RELV', 'Reliv' International')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('MARK', 'Remark Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RRI', 'Remora Royalties')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RNST', 'Renasant Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('REGI', 'Renewable Energy Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ABAC', 'Renmin Tianli Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RCII', 'Rent-A-Center Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RGEN', 'Repligen Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('REPL', 'Replimune Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RBCAA', 'Republic Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('FRBK', 'Republic First Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('REFR', 'Research Frontiers Incorporated')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RSLS', 'ReShape Lifesciences Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RESN', 'Resonant Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RECN', 'Resources Connection')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('HAIR', 'Restoration Robotics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TORC', 'resTORbio')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ROIC', 'Retail Opportunity Investments Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RETO', 'ReTo Eco-Solutions')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RTRX', 'Retrophin')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RVNC', 'Revance Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RVEN', 'Reven Housing REIT')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RVLT', 'Revolution Lighting Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RWLK', 'ReWalk Robotics Ltd')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RFIL', 'RF Industries')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RGCO', 'RGC Resources Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RYTM', 'Rhythm Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RBBN', 'Ribbon Communications Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RIBT', 'RiceBran Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RIBTW', 'RiceBran Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RELL', 'Richardson Electronics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RIGL', 'Rigel Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RNET', 'RigNet')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RMNI', 'Rimini Street')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RIOT', 'Riot Blockchain')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('REDU', 'RISE Education Cayman Ltd')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RTTR', 'Ritter Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RVSB', 'Riverview Bancorp Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RIVE', 'Riverview Financial Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RLJE', 'RLJ Entertainment')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RCKT', 'Rocket Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RMTI', 'Rockwell Medical')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RCKY', 'Rocky Brands')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RMCF', 'Rocky Mountain Chocolate Factory')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ROKU', 'Roku')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ROSE', 'Rosehill Resources Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ROSEU', 'Rosehill Resources Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ROSEW', 'Rosehill Resources Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ROST', 'Ross Stores')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RGLD', 'Royal Gold')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RTIX', 'RTI Surgical')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RBCN', 'Rubicon Technology')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RUBY', 'Rubius Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RMBL', 'RumbleOn')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RUSHA', 'Rush Enterprises')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RUSHB', 'Rush Enterprises')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RUTH', 'Ruth's Hospitality Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RXII', 'RXi Pharmaceuticals Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RXIIW', 'RXi Pharmaceuticals Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RYAAY', 'Ryanair Holdings plc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STBA', 'S&T Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SANW', 'S&W Seed Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCAC', 'Saban Capital Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCACU', 'Saban Capital Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCACW', 'Saban Capital Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBRA', 'Sabra Health Care REIT')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SABR', 'Sabre Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SAEX', 'SAExploration Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SFET', 'Safe-T Group Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SAFT', 'Safety Insurance Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGA', 'Saga Communications')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SAGE', 'Sage Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SAIA', 'Saia')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SALM', 'Salem Media Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SAL', 'Salisbury Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SAFM', 'Sanderson Farms')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SASR', 'Sandy Spring Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGMO', 'Sangamo Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SANM', 'Sanmina Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('GCVRZ', 'Sanofi')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPNS', 'Sapiens International Corporation N.V.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SRPT', 'Sarepta Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SVRA', 'Savara')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBFG', 'SB Financial Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBFGP', 'SB Financial Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBBX', 'SB One Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBAC', 'SBA Communications Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCSC', 'ScanSource')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMIT', 'Schmitt Industries')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCHN', 'Schnitzer Steel Industries')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SRRK', 'Scholar Rock Holding Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCHL', 'Scholastic Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGMS', 'Scientific Games Corp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCPH', 'scPharmaceuticals Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCYX', 'SCYNEXIS')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SEAC', 'SeaChange International')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBCF', 'Seacoast Banking Corporation of Florida')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STX', 'Seagate Technology PLC')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SHIP', 'Seanergy Maritime Holdings Corp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SHIPW', 'Seanergy Maritime Holdings Corp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SHLD', 'Sears Holdings Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SHLDW', 'Sears Holdings Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SHOS', 'Sears Hometown and Outlet Stores')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPNE', 'SeaSpine Holdings Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGEN', 'Seattle Genetics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('EYES', 'Second Sight Medical Products')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('EYESW', 'Second Sight Medical Products')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SECO', 'Secoo Holding Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCWX', 'SecureWorks Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNFCA', 'Security National Financial Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SEIC', 'SEI Investments Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLCT', 'Select Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIR', 'Select Income REIT')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIC', 'Select Interior Concepts')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SELB', 'Selecta Biosciences')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIGI', 'Selective Insurance Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLS', 'SELLAS Life Sciences Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('LEDS', 'SemiLEDS Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMTC', 'Semtech Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SENEA', 'Seneca Foods Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SENEB', 'Seneca Foods Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNES', 'SenesTech')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNH', 'Senior Housing Properties Trust')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNHNI', 'Senior Housing Properties Trust')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNHNL', 'Senior Housing Properties Trust')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('AIHS', 'Senmiao Technology Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNMX', 'Senomyx')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SRTS', 'Sensus Healthcare')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SRTSW', 'Sensus Healthcare')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STNL', 'Sentinel Energy Services Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STNLU', 'Sentinel Energy Services Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STNLW', 'Sentinel Energy Services Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SQBG', 'Sequential Brands Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('MCRB', 'Seres Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SREV', 'ServiceSource International')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SFBS', 'ServisFirst Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SESN', 'Sesen Bio')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SSC', 'Seven Stars Cloud Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SVBI', 'Severn Bancorp Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGBX', 'SG Blocks')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGOC', 'SGOCO Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SEII', 'Sharing Economy International Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMED', 'Sharps Compliance Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SHSP', 'SharpSpring')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SHEN', 'Shenandoah Telecommunications Co')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('PIXY', 'ShiftPixy')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SHLO', 'Shiloh Industries')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TYHT', 'Shineco')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SHPG', 'Shire plc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCVL', 'Shoe Carnival')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SHBI', 'Shore Bancshares Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SSTI', 'ShotSpotter')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SFLY', 'Shutterfly')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIFI', 'SI Financial Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIBN', 'SI-BONE')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIEB', 'Siebert Financial Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNNA', 'Sienna Biopharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIEN', 'Sientra')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('BSRR', 'Sierra Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SRRA', 'Sierra Oncology')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SWIR', 'Sierra Wireless')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIFY', 'Sify Technologies Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIGA', 'SIGA Technologies Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGLB', 'Sigma Labs')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGLBW', 'Sigma Labs')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGMA', 'SigmaTron International')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBNY', 'Signature Bank')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBNYW', 'Signature Bank')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLGN', 'Silgan Holdings Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SILC', 'Silicom Ltd')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLAB', 'Silicon Laboratories')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIMO', 'Silicon Motion Technology Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SAMG', 'Silvercrest Asset Management Group Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SSNT', 'SilverSun Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SFNC', 'Simmons First National Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLP', 'Simulations Plus')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SINA', 'Sina Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBGI', 'Sinclair Broadcast Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SINO', 'Sino-Global Shipping America')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SVA', 'Sinovac Biotech')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIRI', 'Sirius XM Holdings Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SITO', 'SITO Mobile')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SKYS', 'Sky Solar Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SKYW', 'SkyWest')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SWKS', 'Skyworks Solutions')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNBR', 'Sleep Number Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLM', 'SLM Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLMBP', 'SLM Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGH', 'SMART Global Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SND', 'Smart Sand')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMBK', 'SmartFinancial')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMSI', 'Smith Micro Software')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMTX', 'SMTC Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SRAX', 'Social Reality')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCKT', 'Socket Mobile')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SODA', 'SodaStream International Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SOHU', 'Sohu.com Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLRC', 'Solar Capital Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SUNS', 'Solar Senior Capital Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SEDG', 'SolarEdge Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLNO', 'Soleno Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLNOW', 'Soleno Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLGL', 'Sol-Gel Technologies Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLDB', 'Solid Biosciences Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNGX', 'Soligenix')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNGXW', 'Soligenix')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SONC', 'Sonic Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SOFO', 'Sonic Foundry')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNOA', 'Sonoma Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNOAW', 'Sonoma Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SONO', 'Sonos')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPHS', 'Sophiris Bio')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SORL', 'SORL Auto Parts')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SRNE', 'Sorrento Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SOHO', 'Sotherly Hotels Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SOHOB', 'Sotherly Hotels Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SOHOO', 'Sotherly Hotels Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SOHOK', 'Sotherly Hotels LP')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SFBC', 'Sound Financial Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SSB', 'South State Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SFST', 'Southern First Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMBC', 'Southern Missouri Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SONA', 'Southern National Bancorp of Virginia')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBSI', 'Southside Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SP', 'SP Plus Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGRP', 'SPAR Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPKE', 'Spark Energy')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPKEP', 'Spark Energy')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ONCE', 'Spark Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPAR', 'Spartan Motors')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPTN', 'SpartanNash Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('DWFI', 'SPDR Dorsey Wright Fixed Income Allocation ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPPI', 'Spectrum Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPRO', 'Spero Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ANY', 'Sphere 3D Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPEX', 'Spherix Incorporated')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPI', 'SPI Energy Co.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SAVE', 'Spirit Airlines')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STXB', 'Spirit of Texas Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPLK', 'Splunk Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPOK', 'Spok Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPWH', 'Sportsman's Warehouse Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBPH', 'Spring Bank Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('FUND', 'Sprott Focus Trust')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SFM', 'Sprouts Farmers Market')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPSC', 'SPS Commerce')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SSNC', 'SS&C Technologies Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SSLJ', 'SSLJ.com Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SSRM', 'SSR Mining Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STAA', 'STAAR Surgical Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STAF', 'Staffing 360 Solutions')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STMP', 'Stamps.com Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STND', 'Standard AVB Financial Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBLK', 'Star Bulk Carriers Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBLKZ', 'Star Bulk Carriers Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBUX', 'Starbucks Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STFC', 'State Auto Financial Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STBZ', 'State Bank Financial Corporation.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('GASS', 'StealthGas')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STCN', 'Steel Connect')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STLD', 'Steel Dynamics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMRT', 'Stein Mart')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STLR', 'Stellar Acquisition III Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STLRU', 'Stellar Acquisition III Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STLRW', 'Stellar Acquisition III Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBOT', 'Stellar Biotechnologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STML', 'Stemline Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SRCL', 'Stericycle')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBT', 'Sterling Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STRL', 'Sterling Construction Company Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SHOO', 'Steven Madden')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SSFN', 'Stewardship Financial Corp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SFIX', 'Stitch Fix')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SYBT', 'Stock Yards Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('BANX', 'StoneCastle Financial Corp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SSKN', 'Strata Skin Sciences')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SSYS', 'Stratasys')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STRA', 'Strategic Education')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('HNDL', 'Strategy Shares Nasdaq 7HANDL Index ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STRT', 'Strattec Security Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STRS', 'Stratus Properties Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STRM', 'Streamline Health Solutions')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SBBP', 'Strongbridge Biopharma plc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SUMR', 'Summer Infant')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMMF', 'Summit Financial Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SSBI', 'Summit State Bank')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMMT', 'Summit Therapeutics plc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WISA', 'Summit Wireless Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNHY', 'Sun Hydraulics Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNDE', 'Sundance Energy Australia Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNSS', 'Sunesis Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STKL', 'SunOpta')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPWR', 'SunPower Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RUN', 'Sunrun Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SUNW', 'Sunworks')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPCB', 'SuperCom')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SCON', 'Superconductor Technologies Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGC', 'Superior Group of Companies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SUPN', 'Supernus Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SPRT', 'support.com')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SURF', 'Surface Oncology')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGRY', 'Surgery Partners')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SRDX', 'Surmodics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STRO', 'Sutro Biopharma')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SIVB', 'SVB Financial Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SVMK', 'SVMK Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SYKE', 'Sykes Enterprises')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SYMC', 'Symantec Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SYNC', 'Synacor')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SYNL', 'Synalloy Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SYNA', 'Synaptics Incorporated')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNCR', 'Synchronoss Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNDX', 'Syndax Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SYNH', 'Syneos Health')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SGYP', 'Synergy Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SYBX', 'Synlogic')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SNPS', 'Synopsys')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SES', 'Synthesis Energy Systems')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SYPR', 'Sypris Solutions')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SYRS', 'Syros Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TROW', 'T. Rowe Price Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TTOO', 'T2 Biosystems')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRHC', 'Tabula Rasa HealthCare')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCMD', 'Tactile Systems Technology')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TAIT', 'Taitron Components Incorporated')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TTWO', 'Take-Two Interactive Software')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TLND', 'Talend S.A.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TNDM', 'Tandem Diabetes Care')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TLF', 'Tandy Leather Factory')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TANH', 'Tantech Holdings Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TAOP', 'Taoping Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TEDU', 'Tarena International')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TATT', 'TAT Technologies Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TAYD', 'Taylor Devices')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CGBD', 'TCG BDC')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('AMTD', 'TD Ameritrade Holding Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('PETZ', 'TDH Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TECD', 'Tech Data Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCCO', 'Technical Communications Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TTGT', 'TechTarget')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TGLS', 'Tecnoglass Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TGEN', 'Tecogen Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TNAV', 'Telenav')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TLGT', 'Teligent')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TELL', 'Tellurian Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TENB', 'Tenable Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TENX', 'Tenax Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TZAC', 'Tenzing Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TZACU', 'Tenzing Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TZACW', 'Tenzing Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TERP', 'TerraForm Power')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TBNK', 'Territorial Bancorp Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TSRO', 'TESARO')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TSLA', 'Tesla')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TESS', 'TESSCO Technologies Incorporated')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TTEK', 'Tetra Tech')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TTPH', 'Tetraphase Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCBI', 'Texas Capital Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCBIL', 'Texas Capital Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCBIP', 'Texas Capital Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCBIW', 'Texas Capital Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TXN', 'Texas Instruments Incorporated')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TXRH', 'Texas Roadhouse')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TFSL', 'TFS Financial Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TGTX', 'TG Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ANDE', 'The Andersons')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TBBK', 'The Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('BPRN', 'The Bank of Princeton')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CG', 'The Carlyle Group L.P.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCGP', 'The Carlyle Group L.P.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CAKE', 'The Cheesecake Factory Incorporated')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CHEF', 'The Chefs' Warehouse')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCFC', 'The Community Financial Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('DSGX', 'The Descartes Systems Group Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('DXYN', 'The Dixie Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ENSG', 'The Ensign Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XONE', 'The ExOne Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('FBMS', 'The First Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('FLIC', 'The First of Long Island Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('GT', 'The Goodyear Tire & Rubber Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('HABT', 'The Habit Restaurants')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('HCKT', 'The Hackett Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('HAIN', 'The Hain Celestial Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CUBA', 'The Herzfeld Caribbean Basin Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('INTG', 'The Intergroup Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('JYNT', 'The Joint Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('KEYW', 'The KEYW Holding Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('KHC', 'The Kraft Heinz Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('OLD', 'The Long-Term Care ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('LOVE', 'The Lovesac Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('MSG', 'The Madison Square Garden Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('MDCO', 'The Medicines Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('MEET', 'The Meet Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('MIK', 'The Michaels Companies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('MIDD', 'The Middleby Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('NAVG', 'The Navigators Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SLIM', 'The Obesity ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('STKS', 'The ONE Group Hospitality')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ORG', 'The Organics ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('PRSC', 'The Providence Service Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RMR', 'The RMR Group Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMPL', 'The Simply Good Foods Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('SMPLW', 'The Simply Good Foods Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TSG', 'The Stars Group Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TTD', 'The Trade Desk')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ULTI', 'The Ultimate Software Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YORW', 'The York Water Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('NCTY', 'The9 Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TXMD', 'TherapeuticsMD')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRPX', 'Therapix Biosciences Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TBPH', 'Theravance Biopharma')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TST', 'TheStreet')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCRD', 'THL Credit')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TBRG', 'Thunder Bridge Acquisition')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TBRGU', 'Thunder Bridge Acquisition')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TBRGW', 'Thunder Bridge Acquisition')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TIBR', 'Tiberius Acquisition Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TIBRU', 'Tiberius Acquisition Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TIBRW', 'Tiberius Acquisition Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TTS', 'Tile Shop Hldgs')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TLRY', 'Tilray')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TSBK', 'Timberland Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TIPT', 'Tiptree Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TITN', 'Titan Machinery Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TMDI', 'Titan Medical Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TTNP', 'Titan Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TVTY', 'Tivity Health')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TIVO', 'TiVo Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TKKS', 'TKK Symphony Acquisition Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TKKSR', 'TKK Symphony Acquisition Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TKKSU', 'TKK Symphony Acquisition Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TKKSW', 'TKK Symphony Acquisition Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TMUS', 'T-Mobile US')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TMSR', 'TMSR Holding Company Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TOCA', 'Tocagen Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TNXP', 'Tonix Pharmaceuticals Holding Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TISA', 'Top Image Systems')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TOPS', 'TOP Ships Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRCH', 'Torchlight Energy Resources')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRMD', 'TORM plc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TOTA', 'Tottenham Acquisition I Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TOTAR', 'Tottenham Acquisition I Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TOTAU', 'Tottenham Acquisition I Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TOTAW', 'Tottenham Acquisition I Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TBLTU', 'ToughBuilt Industries')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TSEM', 'Tower Semiconductor Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CLUB', 'Town Sports International Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TOWN', 'Towne Bank')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TPIC', 'TPI Composites')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCON', 'TRACON Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TSCO', 'Tractor Supply Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TWMC', 'Trans World Entertainment Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TACT', 'TransAct Technologies Incorporated')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRNS', 'Transcat')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TGA', 'TransGlobe Energy Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TBIO', 'Translate Bio')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TA', 'TravelCenters of America LLC')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TANNI', 'TravelCenters of America LLC')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TANNL', 'TravelCenters of America LLC')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TANNZ', 'TravelCenters of America LLC')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TZOO', 'Travelzoo')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRMT', 'Tremont Mortgage Trust')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRVN', 'Trevena')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TPCO', 'Tribune Publishing Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCDA', 'Tricida')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCBK', 'TriCo Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TDAC', 'Trident Acquisitions Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TDACU', 'Trident Acquisitions Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TDACW', 'Trident Acquisitions Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRIL', 'Trillium Therapeutics Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRS', 'TriMas Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRMB', 'Trimble Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRIB', 'Trinity Biotech plc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TMCX', 'Trinity Merger Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TMCXU', 'Trinity Merger Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TMCXW', 'Trinity Merger Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRIP', 'TripAdvisor')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TSC', 'TriState Capital Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TSCAP', 'TriState Capital Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TBK', 'Triumph Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRVG', 'trivago N.V.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TROV', 'TrovaGene')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRUE', 'TrueCar')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('THST', 'Truett-Hurst')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRUP', 'Trupanion')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRST', 'TrustCo Bank Corp NY')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRMK', 'Trustmark Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TSRI', 'TSR')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TTEC', 'TTEC Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TTMI', 'TTM Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TCX', 'Tucows Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TUES', 'Tuesday Morning Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TOUR', 'Tuniu Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('HEAR', 'Turtle Beach Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TWLV', 'Twelve Seas Investment Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TWLVR', 'Twelve Seas Investment Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TWLVU', 'Twelve Seas Investment Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TWLVW', 'Twelve Seas Investment Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('FOX', 'Twenty-First Century Fox')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('FOXA', 'Twenty-First Century Fox')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TWIN', 'Twin Disc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TRCB', 'Two River Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('TYME', 'Tyme Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('USCR', 'U S Concrete')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('PRTS', 'U.S. Auto Parts Network')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('USEG', 'U.S. Energy Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('GROW', 'U.S. Global Investors')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('USAU', 'U.S. Gold Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UBNT', 'Ubiquiti Networks')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UFPT', 'UFP Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ULTA', 'Ulta Beauty')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UCTT', 'Ultra Clean Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UPL', 'Ultra Petroleum Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('RARE', 'Ultragenyx Pharmaceutical Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ULBI', 'Ultralife Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UMBF', 'UMB Financial Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UMPQ', 'Umpqua Holdings Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UNAM', 'Unico American Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UBSH', 'Union Bankshares Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UNB', 'Union Bankshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('QURE', 'uniQure N.V.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UBCP', 'United Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UBOH', 'United Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UBSI', 'United Bankshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UCBI', 'United Community Banks')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UCFC', 'United Community Financial Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UAL', 'United Continental Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UBNK', 'United Financial Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UFCS', 'United Fire Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UIHC', 'United Insurance Holdings Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UNFI', 'United Natural Foods')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UBFO', 'United Security Bancshares')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('USLM', 'United States Lime & Minerals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UTHR', 'United Therapeutics Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UG', 'United-Guardian')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UNIT', 'Uniti Group Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UNTY', 'Unity Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UBX', 'Unity Biotechnology')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('OLED', 'Universal Display Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UEIC', 'Universal Electronics Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UFPI', 'Universal Forest Products')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ULH', 'Universal Logistics Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('USAP', 'Universal Stainless & Alloy Products')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UVSP', 'Univest Corporation of Pennsylvania')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UMRX', 'Unum Therapeutics Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UPLD', 'Upland Software')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UPWK', 'Upwork Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UONE', 'Urban One')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UONEK', 'Urban One')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('URBN', 'Urban Outfitters')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('URGN', 'UroGen Pharma Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UROV', 'Urovant Sciences Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ECOL', 'US Ecology')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('USAT', 'USA Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('USATP', 'USA Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('USAK', 'USA Truck')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UTMD', 'Utah Medical Products')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UTSI', 'UTStarcom Holdings Corp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('UXIN', 'Uxin Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VCNX', 'Vaccinex')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VLRX', 'Valeritas Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VALX', 'Validea Market Legends ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VLY', 'Valley National Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VLYPO', 'Valley National Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VLYPP', 'Valley National Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VLYWW', 'Valley National Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTEC', 'Valtech SE')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VALU', 'Value Line')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VNDA', 'Vanda Pharmaceuticals Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('BBH', 'VanEck Vectors Biotech ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('GNRX', 'VanEck Vectors Generic Drugs ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('PPH', 'VanEck Vectors Pharmaceutical ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VWOB', 'Vanguard Emerging Markets Government Bond ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VNQI', 'Vanguard Global ex-U.S. Real Estate ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VCIT', 'Vanguard Intermediate-Term Corporate Bond ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VGIT', 'Vanguard Intermediate-Term Treasury ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VIGI', 'Vanguard International Dividend Appreciation ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VYMI', 'Vanguard International High Dividend Yield ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VCLT', 'Vanguard Long-Term Corporate Bond ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VGLT', 'Vanguard Long-Treasury ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VMBS', 'Vanguard Mortgage-Backed Securities ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VONE', 'Vanguard Russell 1000 ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VONG', 'Vanguard Russell 1000 Growth ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VONV', 'Vanguard Russell 1000 Value ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTWO', 'Vanguard Russell 2000 ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTWG', 'Vanguard Russell 2000 Growth ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTWV', 'Vanguard Russell 2000 Value ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTHR', 'Vanguard Russell 3000 ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VCSH', 'Vanguard Short-Term Corporate Bond ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTIP', 'Vanguard Short-Term Inflation-Protected Securities Index Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VGSH', 'Vanguard Short-Term Treasury ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('BND', 'Vanguard Total Bond Market ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTC', 'Vanguard Total Corporate Bond ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('BNDX', 'Vanguard Total International Bond ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VXUS', 'Vanguard Total International Stock ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('BNDW', 'Vanguard Total World Bond ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VEAC', 'Vantage Energy Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VEACU', 'Vantage Energy Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VEACW', 'Vantage Energy Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VREX', 'Varex Imaging Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRNS', 'Varonis Systems')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VBLT', 'Vascular Biogenics Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VXRT', 'Vaxart')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VBIV', 'VBI Vaccines')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTIQ', 'VectoIQ Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTIQU', 'VectoIQ Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTIQW', 'VectoIQ Acquisition Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VECO', 'Veeco Instruments Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VEON', 'VEON Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRA', 'Vera Bradley')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VCYT', 'Veracyte')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VSTM', 'Verastem')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VCEL', 'Vericel Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRNT', 'Verint Systems Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRSN', 'VeriSign')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRSK', 'Verisk Analytics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VBTX', 'Veritex Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VERI', 'Veritone')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRML', 'Vermillion')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRNA', 'Verona Pharma plc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRRM', 'Verra Mobility Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRRMW', 'Verra Mobility Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRCA', 'Verrica Pharmaceuticals Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTNR', 'Vertex Energy')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRTX', 'Vertex Pharmaceuticals Incorporated')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VERU', 'Veru Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VIA', 'Viacom Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VIAB', 'Viacom Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VSAT', 'ViaSat')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VIAV', 'Viavi Solutions Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VICL', 'Vical Incorporated')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VICR', 'Vicor Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VCTR', 'Victory Capital Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CIZ', 'VictoryShares Developed Enhanced Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VSDA', 'VictoryShares Dividend Accelerator ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CEY', 'VictoryShares Emerging Market High Div Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CEZ', 'VictoryShares Emerging Market Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CID', 'VictoryShares International High Div Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CIL', 'VictoryShares International Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CFO', 'VictoryShares US 500 Enhanced Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CFA', 'VictoryShares US 500 Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CSF', 'VictoryShares US Discovery Enhanced Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CDC', 'VictoryShares US EQ Income Enhanced Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CDL', 'VictoryShares US Large Cap High Div Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VSMV', 'VictoryShares US Multi-Factor Minimum Volatility ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CSB', 'VictoryShares US Small Cap High Div Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CSA', 'VictoryShares US Small Cap Volatility Wtd ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRAY', 'ViewRay')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VKTX', 'Viking Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VKTXW', 'Viking Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VBFC', 'Village Bank and Trust Financial Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VLGEA', 'Village Super Market')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VIOT', 'Viomi Technology Co.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VNOM', 'Viper Energy Partners LP')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VIRC', 'Virco Manufacturing Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTSI', 'VirTra')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VIRT', 'Virtu Financial')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRTS', 'Virtus Investment Partners')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRTSP', 'Virtus Investment Partners')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('BBC', 'Virtus LifeSci Biotech Clinical Trials ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('BBP', 'Virtus LifeSci Biotech Products ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VRTU', 'Virtusa Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTGN', 'VistaGen Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VC', 'Visteon Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTL', 'Vital Therapies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VIVE', 'Viveve Medical')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VVPR', 'VivoPower International PLC')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VVUS', 'VIVUS')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VOD', 'Vodafone Group Plc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VOXX', 'VOXX International Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VYGR', 'Voyager Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VSEC', 'VSE Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VTVT', 'vTv Therapeutics Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('VUZI', 'Vuzix Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WBA', 'Walgreens Boots Alliance')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WAFD', 'Washington Federal')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WAFDW', 'Washington Federal')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WASH', 'Washington Trust Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WSBF', 'Waterstone Financial')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WVE', 'WAVE Life Sciences Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WSTG', 'Wayside Technology Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WCFB', 'WCF Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WDFC', 'WD-40 Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WB', 'Weibo Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WTW', 'Weight Watchers International Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WEBK', 'Wellesley Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WEN', 'Wendy's Company (The)')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WERN', 'Werner Enterprises')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WSBC', 'WesBanco')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WTBA', 'West Bancorporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WABC', 'Westamerica Bancorporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WSTL', 'Westell Technologies')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WBND', 'Western Asset Total Return ETF')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WDC', 'Western Digital Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WNEB', 'Western New England Bancorp')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WPRT', 'Westport Fuel Systems Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WWR', 'Westwater Resources')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WEYS', 'Weyco Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WHLR', 'Wheeler Real Estate Investment Trust')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WHLRD', 'Wheeler Real Estate Investment Trust')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WHLRP', 'Wheeler Real Estate Investment Trust')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WHLRW', 'Wheeler Real Estate Investment Trust')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WHF', 'WhiteHorse Finance')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WHLM', 'Wilhelmina International')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WVVI', 'Willamette Valley Vineyards')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WVVIP', 'Willamette Valley Vineyards')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WLDN', 'Willdan Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WLFC', 'Willis Lease Finance Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WLTW', 'Willis Towers Watson Public Limited Company')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WSC', 'WillScot Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WIN', 'Windstream Holdings')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WING', 'Wingstop Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WINA', 'Winmark Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WINS', 'Wins Finance Holdings Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WTFC', 'Wintrust Financial Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WTFCM', 'Wintrust Financial Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WTFCW', 'Wintrust Financial Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('AGND', 'WisdomTree Barclays Negative Duration U.S. Aggregate Bond Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('CXSE', 'WisdomTree China ex-State-Owned Enterprises Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('EMCG', 'WisdomTree Emerging Markets Consumer Growth Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('EMCB', 'WisdomTree Emerging Markets Corporate Bond Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('DGRE', 'WisdomTree Emerging Markets Quality Dividend Growth Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('DXGE', 'WisdomTree Germany Hedged Equity Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('HYZD', 'WisdomTree Interest Rate Hedged High Yield Bond Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('AGZD', 'WisdomTree Interest Rate Hedged U.S. Aggregate Bond Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WETF', 'WisdomTree Investments')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('DXJS', 'WisdomTree Japan Hedged SmallCap Equity Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('GULF', 'WisdomTree Middle East Dividend Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('HYND', 'WisdomTree Negative Duration High Yield Bond Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('DGRW', 'WisdomTree U.S. Quality Dividend Growth Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('DGRS', 'WisdomTree U.S. SmallCap Quality Dividend Growth Fund')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WIX', 'Wix.com Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WWD', 'Woodward')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WDAY', 'Workday')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WKHS', 'Workhorse Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WRLD', 'World Acceptance Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WMGI', 'Wright Medical Group N.V.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WMGIZ', 'Wright Medical Group N.V.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WSFS', 'WSFS Financial Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WSCI', 'WSI Industries Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WVFC', 'WVS Financial Corp.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('WYNN', 'Wynn Resorts')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XBIT', 'XBiotech Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XELB', 'Xcel Brands')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XEL', 'Xcel Energy Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XNCR', 'Xencor')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XBIO', 'Xenetic Biosciences')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XENE', 'Xenon Pharmaceuticals Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XERS', 'Xeris Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XGTI', 'XG Technology')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XLNX', 'Xilinx')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XOMA', 'XOMA Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XPER', 'Xperi Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XSPA', 'XpresSpa Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XTLB', 'XTL Biopharmaceuticals Ltd.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('XNET', 'Xunlei Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YNDX', 'Yandex N.V.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YRIV', 'Yangtze River Port and Logistics Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YTRA', 'Yatra Online')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YTEN', 'Yield10 Bioscience')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YIN', 'Yintech Investment Holdings Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YMAB', 'Y-mAbs Therapeutics')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YOGA', 'YogaWorks')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YGYI', 'Youngevity International')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YRCW', 'YRC Worldwide')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YECO', 'Yulong Eco-Materials Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('YY', 'YY Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZFGN', 'Zafgen')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZAGG', 'ZAGG Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZLAB', 'Zai Lab Limited')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZEAL', 'Zealand Pharma A/S')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZBRA', 'Zebra Technologies Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('Z', 'Zillow Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZG', 'Zillow Group')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZN', 'Zion Oil & Gas Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZNWAA', 'Zion Oil & Gas Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZION', 'Zions Bancorporation N.A.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZIONW', 'Zions Bancorporation N.A.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZIONZ', 'Zions Bancorporation N.A.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZIOP', 'ZIOPHARM Oncology Inc')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZIXI', 'Zix Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZKIN', 'ZK International Group Co.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZGNX', 'Zogenix')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZSAN', 'Zosano Pharma Corporation')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZS', 'Zscaler')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZUMZ', 'Zumiez Inc.')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZYNE', 'Zynerba Pharmaceuticals')
INSERT INTO asset_pricing (ticker_symbol, company_name) VALUES ('ZNGA', 'Zynga Inc.')

